server:
  port: 0

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  datasource:
    driver-class-name: org.postgresql.Driver

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.bookingsystem.*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

kafka:
  booking:
    topics:
      booking-created: booking-created-topic
  payment:
    topics:
      payment-success: payment-success-topic
      payment-failed: payment-failed-topic