server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/booking_dev
    #username: postgres
    #password: 1234
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${SPRING_JPA_SHOW_SQL:false}

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: booking-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.bookingsystem.*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    booking:
      topics:
        booking-created: booking-created-topic
    payment:
      topics:
        payment-success: payment-success-topic
        payment-failed: payment-failed-topic