server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_dev
#    username: postgres
#    password: 1234
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update